### ISSUE TITLE
Outdoor Temperature

### ISSUE THREAD

**Issue by OnewheelerSA** [shaundekok/rainpoint#3]
Thanks for this integration. Got the rain gauge working perfectly but temperature sensor wont work. I am getting the following error in node red. Any ideas how to resolve this?

function : (error)
"TypeError: Cannot read properties of null (reading 'split')"

**Comment by shaundekok** [comment]
Hi, 
Please share you home with me and I will have a look: smdk0404@hotmail.com

**Comment by OnewheelerSA** [comment]
My rainpoint home? I installed the NodeRed flow as you suggested. I only have the rain gauge and the temp/humidity sensor. The rain gauge readings are also inaccurate when they pull them in Node-Red. It's showing values when there actually hasn't been any rain. So thats also weird.

**Comment by shaundekok** [comment]
Correct, I only had 1 account to test the flow.

Invite my account from 'Me' → 'Home management' → your home → 'Members'

Regards,
Shaun de Kok
+27 (0) 83 263 0767
________________________________

**Comment by OnewheelerSA** [comment]
Ahh ok cool. 
I have just added you to my home now. 

Let me know once you have been able to test it out.

**Comment by shaundekok** [comment]
@OnewheelerSA Please test the new flow I just uploaded.

**Comment by OnewheelerSA** [comment]
@shaundekok new flow worked perfectly. Thanks so much. Appreciate that. 

Still getting one error but doesn't seem to matter as it's all working. 
[node: function 11]
function : (error)
"TypeError: Cannot read properties of undefined (reading 'model')"

**Comment by OnewheelerSA** [comment]
Would you mind sharing this dashboard with me?

![rainpoint](https://github.com/user-attachments/assets/c45d598b-512b-4dad-a8f8-764fec846bcd)

**Comment by shaundekok** [comment]
> @shaundekok new flow worked perfectly. Thanks so much. Appreciate that.
> 
> Still getting one error but doesn't seem to matter as it's all working. [node: function 11] function : (error) "TypeError: Cannot read properties of undefined (reading 'model')"

This error does not matter

**Comment by shaundekok** [comment]
Hi, I uploaded the images in a folder called sensor_images and you can import the dashboard.yamel file.

**Comment by shaundekok** [comment]
Original issue resolved

**Comment by OnewheelerSA** [comment]
Great thanks so much for uploading those.
