### ISSUE TITLE
Video guide request

### ISSUE THREAD

**Issue by reganerasmus** [shaundekok/rainpoint#4]
I know this isn't an issue, so apologies for that :)
I have been looking for a South African product i can integrate into my HA - the problem is that i am a novice on HA and have built every element of my solution from watching YouTube.

Would it be possible for you to help me and guys like me integrate the RainPoint products into HA - i have no experience with Node-Red for example. I haven't purchased any items from RainPoint yet  -  Rudi said i should ask you first :)

**Comment by shaundekok** [comment]
Hi, have a look at the following. It will show you show to import the JSON File: https://www.youtube.com/watch?v=yJXHiBLubAc&pp=ygUgSG93IHRvIGltcG9ydCBqc29uIGludG8gbm9kZS1yZWQ%3D

**Comment by reganerasmus** [comment]
ok thanks -
